name: Report BUG
description: Crie um relatório para nos ajudar a melhorar.
title: "[BUG] "
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please make sure you provide all the requested information to help us address the issue efficiently.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm these before submitting your issue
      options:
        - label: I have checked that my issue doesn't exist yet in the [issue tracker](https://github.com/alliedmodders/metamod-source/issues)
          required: true
        - label: I am running Metamod:Source with a dedicated server rather than a listen server
          required: true

  - type: input
    id: swiftlys2-version
    attributes:
      label: Versão SwiftlyS2
      description: Versão do SwiftlyS2 que esta usando?
      placeholder: "E.x., v1.1.0"
    validations:
      required: true

  - type: input
    id: metamod-version
    attributes:
      label: Versão Metamod:Source
      description: Versão do Metamod que esta usando?
      placeholder: "E.x., 2.0 - build 1375"
    validations:
      required: true

  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Por favor, forneça uma descrição clara e concisa do bug.
      placeholder: O que aconteceu? O que você esperava que acontecesse?
    validations:
      required: true

  - type: textarea
    id: reproducao
    attributes:
      label: Como reproduzir
      description: Por favor, forneça os passos necessários para reproduzir o problema.
      placeholder: |
        *Se possível, inclua no menor detalhe possível etapas para reproduzir o problema.*

        *Além disso, por favor, deixe claro se você consegue reproduzir esse problema de forma consistente com a descrição fornecida.*

        1. Primeiro passo...
        2. Segundo passo...
        3. ...

  - type: textarea
    id: logs
    attributes:
      label: Logs de erros
      description: |
        Por favor, forneça qualquer saída de log relevante. Ela será formatada automaticamente em código, portanto, não é necessário usar crases.
      render: shell
