name: Reportar BUG
description: Crie um relatório de BUG para nos ajudar a corrigir e melhorar a nossa comunidade.
title: "[BUG] "
labels: ["BUG"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por dedicar seu tempo para preencher este relatório de erro! Certifique-se de fornecer todas as informações solicitadas para nos ajudar a resolver o problema com eficiência.

  - type: checkboxes
    id: prerequisitos
    attributes:
      label: Pré-requisitos
      description: Por favor, confirme essas informações antes de enviar sua solicitação.
      options:
        - label: Verifiquei que meu problema ainda não existe no [**Issues**](https://github.com/ZK-Servidores/.github/issues)
          required: true

  - type: input
    id: swiftlys2-version
    attributes:
      label: Versão SwiftlyS2
      description: Versão do SwiftlyS2 que esta usando?
      placeholder: "E.x., v1.1.0"
    validations:
      required: true

  - type: input
    id: metamod-version
    attributes:
      label: Versão Metamod:Source
      description: Versão do Metamod que esta usando?
      placeholder: "E.x., 2.0 - build 1375"
    validations:
      required: true

  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Por favor, forneça uma descrição clara e concisa do bug.
      placeholder: O que aconteceu? O que você esperava que acontecesse?
    validations:
      required: true

  - type: textarea
    id: reproducao
    attributes:
      label: Como reproduzir
      description: Por favor, forneça os passos necessários para reproduzir o bug.
      placeholder: |
        *Se possível, inclua no menor detalhe possível etapas para reproduzir o problema.*

        *Passos para reproduzir o comportamento:*
        
        1. Vá para '...'
        2. Clique em '....'
        3. Role para baixo até '....'
        4. Veja o erro
    validations:
      required: true
      
  - type: textarea
    id: prints-videos
    attributes:
      label: Prints & Vídeos
      description: Por favor, forneça prints e vídeos referente ao bug.
      placeholder: |
        *Se possível, inclua as prints e vídeos direto no issues, evite links. - Podem ficar offline com o tempo!*
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs de erros
      description: |
        Por favor, forneça qualquer saída de log relevante. Ela será formatada automaticamente em código, portanto, não é necessário usar crases.
      render: shell
      
  - type: textarea
    id: metalista
    attributes:
      label: Lista de Plugins Metamod
      description: |
        Copie e cole o resultado do **`meta list`** do console do servidor aqui.
      render: shell
      
  - type: textarea
    id: swiftlys2-plugislist
    attributes:
      label: Lista de Plugins SwiftlyS2
      description: |
        Copie e cole o resultado do **`sw plugins list`** do console do servidor aqui.
      render: shell
