name: Solicitação de Recurso
description: Crie um relatório para solicitar um recurso e melhorar a nossa comunidade.
title: "[REQ] "
labels: ["SUGGESTION"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por dedicar seu tempo para preencher este relatório de solicitação de recurso! Certifique-se de fornecer máximo de detalhes possível sobre o recurso que gostaria.

  - type: checkboxes
    id: prerequisitos
    attributes:
      label: Pré-requisitos
      description: Por favor, confirme essas informações antes de enviar sua solicitação.
      options:
        - label: Verifiquei que minha solicitação de recurso ainda não existe no [**Issues**](https://github.com/ZK-Servidores/.github/issues)
          required: true
        - label: Verifiquei que minha solicitação de recurso ainda não é um [**Privilégio VIP**](https://zkservidores.com/shop)
          required: true

  - type: input
    id: game-mode
    attributes:
      label: Modo de Jogo
      description: Para qual modo de jogo este recurso seria?
      placeholder: "E.x., Competitivo, Retak, etc"
    validations:
      required: true

  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Por favor, forneça uma descrição clara e concisa da solicitação de recurso.
      placeholder: O que você espera com este recurso, como ele vai funcionar e etc?
    validations:
      required: true
 